# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: a.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='a.proto',
  package='questionanswer',
  serialized_pb=_b('\n\x07\x61.proto\x12\x0equestionanswer\"\xb6\x01\n\x0eQuestionAnswer\x12\x10\n\x08question\x18\x01 \x01(\t\x12\x0f\n\x07\x61nswer1\x18\x02 \x01(\t\x12\x0f\n\x07\x61nswer2\x18\x03 \x01(\t\x12/\n\x07next_q1\x18\x04 \x01(\x0b\x32\x1e.questionanswer.QuestionAnswer\x12/\n\x07next_q2\x18\x05 \x01(\x0b\x32\x1e.questionanswer.QuestionAnswer\x12\x0e\n\x06\x61nimal\x18\x06 \x01(\t')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_QUESTIONANSWER = _descriptor.Descriptor(
  name='QuestionAnswer',
  full_name='questionanswer.QuestionAnswer',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='question', full_name='questionanswer.QuestionAnswer.question', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='answer1', full_name='questionanswer.QuestionAnswer.answer1', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='answer2', full_name='questionanswer.QuestionAnswer.answer2', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='next_q1', full_name='questionanswer.QuestionAnswer.next_q1', index=3,
      number=4, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='next_q2', full_name='questionanswer.QuestionAnswer.next_q2', index=4,
      number=5, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='animal', full_name='questionanswer.QuestionAnswer.animal', index=5,
      number=6, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=28,
  serialized_end=210,
)

_QUESTIONANSWER.fields_by_name['next_q1'].message_type = _QUESTIONANSWER
_QUESTIONANSWER.fields_by_name['next_q2'].message_type = _QUESTIONANSWER
DESCRIPTOR.message_types_by_name['QuestionAnswer'] = _QUESTIONANSWER

QuestionAnswer = _reflection.GeneratedProtocolMessageType('QuestionAnswer', (_message.Message,), dict(
  DESCRIPTOR = _QUESTIONANSWER,
  __module__ = 'a_pb2'
  # @@protoc_insertion_point(class_scope:questionanswer.QuestionAnswer)
  ))
_sym_db.RegisterMessage(QuestionAnswer)


# @@protoc_insertion_point(module_scope)
